### ISSUE TITLE
pattern {tid} not shows the source threadid by async sink

### ISSUE THREAD

**Issue by nneesshh** [SpriteOvO/spdlog-rs#28]
https://github.com/nneesshh/spdlog-rs/commit/78e92c2890c4c62928c6daa0aa1685fdd383ee23

I forked and test by example "05_custom_formatter.rs"

the {tid} shows the thread id of threadpool, not the log source thread.

It should emmbed a tid in Record struct

**Comment by SpriteOvO** [comment]
Fix released in [v0.3.9](https://github.com/SpriteOvO/spdlog-rs/releases/tag/v0.3.9), thanks!
