### ISSUE TITLE
[Feature Request] Allow calling other macros in logging macros

### ISSUE THREAD

**Issue by SpriteOvO** [SpriteOvO/spdlog-rs#58]
## Is your feature request related to a problem? Please describe.

For [anyhow](https://crates.io/crates/anyhow) users, patterns like

```rust
result.map_err(|err| anyhow!("something went wrong: {err}"));

if x != y {
    do_something_else();
    bail!("something mismatched. {x}!={y}");
}

ensure!(x == y, "something mismatched. {x}!={y}");
```

are very common in their projects. Some users may also want to log the error message before returning. Currently, they can only do it in this way

```rust
result.map_err(|err| {
    error!("something went wrong: {err}")
    anyhow!("something went wrong: {err}")
});

if x != y {
    do_something_else();
    critical!("something mismatched. {x}!={y}");
    bail!("something mismatched. {x}!={y}");
}
```

This is obviously a bit verbose.

## Describe the solution you'd like

Implement a additional optional syntax to the logging macros - log the error message first and then call the specified macro with formatting arguments only.

For syntax, I have some thoughts, but haven't thought hard enough about which is better.

```rust
error!(anyhow, "something went wrong: {err}");
error!(then anyhow, "something went wrong: {err}");
error!(then: anyhow, "something went wrong: {err}"); // Because we already have syntax `error!(logger: xxx, "yyy")`
error!(then(anyhow), "something went wrong: {err}");
error!(.then(anyhow), "something went wrong: {err}");

// For future consideration? Call the specified macro first and then log
error!(anyhow then, "something went wrong: {err}");

// Other ideas?
```

I prefer not to use at least the first one, as it may create ambiguity with future new syntax.

For implementation, it should not be very difficult, just match the new syntax and call the specified macro in the tail of macro.

**Comment by SpriteOvO** [comment]
Rethinking it, if users do a `anyhow!` or `bail!`, then the error will be handled in the upper callers, so a log can be output there.

Unless there are further meaningful real-world examples, I think this feature is unnecessary.

**Comment by Lancern** [comment]
> Rethinking it, if users do a `anyhow!` or `bail!`, then the error will be handled at the upper caller sites, so a log would be output there.

Well, this is not always the case and I believe there's still use cases of this feature. In some design guidelines log messages are written at the very site where the errors are produced, not at the error handling site.

**Comment by SpriteOvO** [comment]
> In some design guidelines log messages are written at the very site where the errors are produced, not at the error handling site.

Right, but in that case, they are most likely to (or should?) log and then return a `None` instead of an `Err` with the same log text.
