### ISSUE TITLE
The logs are not updated in time, even set the flush period

### ISSUE THREAD

**Issue by sopaco** [SpriteOvO/spdlog-rs#76]
## Describe the bug
When I use the RotatingFileSink method to output logs to a file, the logs are not updated in time, even set the flush perid; they only get updated when I exit the program.

## To Reproduce
```rs
let path = get_appdata_file_in_dir("logs", format!("app{}.log", log_section.log_name_tail));
            info!("the log was enabled in disk mode and would be recorded in {:?} with date-named mode", path);
            let new_logger = spdlog::default_logger().fork_with(|new| {
                let file_sink = Arc::new(
                    RotatingFileSink::builder()
                        .base_path(path)
                        .rotation_policy(RotationPolicy::Daily { hour: 0, minute: 0 })
                        .build()?,
                );
                new.sinks_mut().push(file_sink);
                Ok(())
            })?;
            new_logger.set_flush_period(Some(Duration::from_secs(3)));
            spdlog::set_default_logger(new_logger);
            specify_logger_format(&spdlog::default_logger());
            info!("the log was enabled and would be recorded in the log file");
            Ok(())
```
``` rs
fn specify_logger_format(logger: &Arc<Logger>) {
    let new_formatter = Box::new(PatternFormatter::new(pattern!(
        "[{date} {time}.{millisecond}] [thread-{tid}] [{^{level}}] {payload}{eol}"
    )));

    for sink in logger.sinks() {
        sink.set_formatter(new_formatter.clone())
    }
}
```
## Expected behavior
After the program initializes spdlog and calls methods like info!(..), warn!(...), the logs are updated in real time, for example, new log content can be traced using tail -f.

## Environments
 - OS: Mac OS
 - Version: Sonoma 14.5
 - rustc 1.81.0 (eeb90cda1 2024-09-04)
- spdlog：0.4.0

**Comment by SpriteOvO** [comment]
Since this issue is already closed by the author, I assume there is no problem with it.

**Comment by blim8183** [comment]
@sopaco did you figure out what you were doing wrong? i'm having a similar issue

**Comment by SpriteOvO** [comment]
@blim8183 Hi, you can created a new issue and provide a minimal reproducible example so I can help you find out the problem.
